#!/usr/bin/env python3
"""
GPU Base Capability Profiler using OpenCL with automatic test configuration generation
Detects GPU basic capability envelope and generates optimized test configurations for batch.py
"""

import time
import json
import argparse
import sys
import os
import math
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Any, Tuple
import numpy as np

try:
    import pyopencl as cl
    import pyopencl.array as cl_array
    PYOPENCL_AVAILABLE = True
except ImportError:
    PYOPENCL_AVAILABLE = False
    print("Warning: PyOpenCL not available, GPU benchmark will be skipped")

# 用于生成YAML配置
try:
    import yaml
    YAML_AVAILABLE = True
except ImportError:
    YAML_AVAILABLE = False
    print("Warning: PyYAML not available, YAML configuration generation will be skipped")


@dataclass
class DeviceInfo:
    """GPU device basic information"""
    name: str = ""
    vendor: str = ""
    version: str = ""
    driver_version: str = ""
    device_type: str = ""
    platform_name: str = ""
    platform_vendor: str = ""
    
    # Compute resources
    max_compute_units: int = 0
    max_work_group_size: int = 0
    max_work_item_dimensions: int = 0
    max_work_item_sizes: List[int] = field(default_factory=list)
    preferred_vector_width_char: int = 0
    preferred_vector_width_short: int = 0
    preferred_vector_width_int: int = 0
    preferred_vector_width_long: int = 0
    preferred_vector_width_float: int = 0
    preferred_vector_width_double: int = 0
    preferred_work_group_size_multiple: int = 0
    native_vector_width_char: int = 0
    native_vector_width_short: int = 0
    native_vector_width_int: int = 0
    native_vector_width_long: int = 0
    native_vector_width_float: int = 0
    native_vector_width_double: int = 0
    
    # Memory architecture
    global_mem_size: int = 0  # bytes
    global_mem_cache_size: int = 0  # bytes
    global_mem_cache_type: str = ""
    global_mem_cacheline_size: int = 0  # bytes
    local_mem_size: int = 0  # bytes
    local_mem_type: str = ""
    constant_buffer_size: int = 0  # bytes
    max_mem_alloc_size: int = 0  # bytes
    max_parameter_size: int = 0  # bytes
    
    # Clock and frequency
    max_clock_frequency: int = 0  # MHz
    profiling_timer_resolution: int = 0  # ns
    
    # Extension support
    extensions: List[str] = field(default_factory=list)
    fp16_support: bool = False
    fp64_support: bool = False
    int64_support: bool = False
    
    # Execution capabilities
    command_queue_properties: List[str] = field(default_factory=list)
    error_correction_support: bool = False
    endian_little: bool = True
    available: bool = True
    compiler_available: bool = True
    linker_available: bool = True
    unified_memory: bool = False


@dataclass
class BandwidthResult:
    """Bandwidth test results"""
    test_name: str = ""
    transfer_size_bytes: int = 0
    transfer_time_ms: float = 0.0
    bandwidth_gbs: float = 0.0
    operations_per_second: float = 0.0
    notes: str = ""


@dataclass
class ConstraintTest:
    """Constraint test results"""
    test_name: str = ""
    parameter_name: str = ""
    max_value: int = 0
    optimal_value: int = 0
    passed: bool = True
    notes: str = ""


@dataclass
class CapabilityReport:
    """GPU capability envelope report"""
    device_info: DeviceInfo = field(default_factory=DeviceInfo)
    bandwidth_results: List[BandwidthResult] = field(default_factory=list)
    constraint_tests: List[ConstraintTest] = field(default_factory=list)
    precision_support: Dict[str, bool] = field(default_factory=dict)
    recommended_settings: Dict[str, Any] = field(default_factory=dict)
    
    timestamp: str = ""
    test_duration_seconds: float = 0.0


@dataclass
class TestConfiguration:
    """Generated test configuration for a specific benchmark"""
    benchmark_type: str  # "trajectory", "monte_carlo", "nbody"
    precision: str  # "fp16", "fp32", "fp64"
    recommended_params: Dict[str, Any]  # Recommended parameters for the test
    estimated_runtime: float  # Estimated runtime in seconds
    confidence_level: float  # 0.0 to 1.0
    safety_factor: float  # 0.0 to 1.0
    notes: str = ""


@dataclass 
class AutoGeneratedConfig:
    """Automatically generated GPU test configuration for batch.py"""
    device_info: Dict[str, Any]
    generation_timestamp: str
    generation_parameters: Dict[str, Any]
    test_configurations: List[TestConfiguration]
    batch_config: Dict[str, Any]  # Full batch.py configuration
    summary: Dict[str, Any]


class GPUBaseCapability:
    """GPU basic capability detector with automatic test configuration generation"""
    
    def __init__(self, platform_idx: Optional[int] = None, 
                 device_idx: Optional[int] = None,
                 verbose: bool = True):
        """
        Initialize GPU capability detector
        
        Args:
            platform_idx: OpenCL platform index, defaults to first
            device_idx: Device index, defaults to first GPU device
            verbose: Whether to print detailed information
        """
        if not PYOPENCL_AVAILABLE:
            raise RuntimeError("PyOpenCL not available")
        
        self.verbose = verbose
        self.context = None
        self.queue = None
        self.device = None
        self.platform = None
        
        # Initialize OpenCL environment
        self._init_opencl(platform_idx, device_idx)
        
        # Test results storage
        self.report = CapabilityReport()
        self.report.timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        
        # Configuration generation parameters
        self.config_params = {
            "target_runtime_per_test": 10.0,  # Target runtime per test in seconds
            "max_total_runtime": 300.0,  # Maximum total runtime in seconds
            "memory_safety_factor": 0.7,  # Use only 70% of available memory
            "confidence_threshold": 0.8,  # Minimum confidence level
            "safety_threshold": 0.7,  # Minimum safety factor
            "min_test_iterations": 3,  # Minimum number of test iterations
            "max_test_iterations": 10,  # Maximum number of test iterations
            "warmup_iterations": 2,  # Number of warmup iterations
        }
    
    def _print(self, msg: str, level: str = "INFO"):
        """Print information"""
        if self.verbose:
            timestamp = time.strftime("%H:%M:%S")
            print(f"[{timestamp}] [{level}] {msg}")
    
    def _init_opencl(self, platform_idx: Optional[int] = None, 
                    device_idx: Optional[int] = None):
        """Initialize OpenCL environment"""
        self._print("Initializing OpenCL environment...")
        
        # Get platform list
        platforms = cl.get_platforms()
        if not platforms:
            raise RuntimeError("No OpenCL platforms found")
        
        # Select platform
        if platform_idx is not None and platform_idx < len(platforms):
            self.platform = platforms[platform_idx]
        else:
            self.platform = platforms[0]
        
        self._print(f"Selected platform: {self.platform.name}")
        self._print(f"Platform vendor: {self.platform.vendor}")
        
        # Prefer GPU devices
        devices = self.platform.get_devices(cl.device_type.GPU)
        if not devices:
            devices = self.platform.get_devices(cl.device_type.ALL)
            self._print("No GPU found, falling back to any device type")
        
        if not devices:
            raise RuntimeError("No OpenCL devices found")
        
        # Select device
        if device_idx is not None and device_idx < len(devices):
            self.device = devices[device_idx]
        else:
            self.device = devices[0]
        
        # Create context and command queue
        self.context = cl.Context([self.device])
        
        # Try to enable profiling, but not mandatory
        try:
            self.queue = cl.CommandQueue(self.context, 
                                        properties=cl.command_queue_properties.PROFILING_ENABLE)
        except:
            self.queue = cl.CommandQueue(self.context)
            self._print("Profiling not available, using basic command queue")
    
    def collect_device_info(self) -> DeviceInfo:
        """Collect device basic information"""
        self._print("Collecting device information...")
        
        info = DeviceInfo()
        
        # Basic information
        info.name = self.device.name
        info.vendor = self.device.vendor
        info.version = self.device.version
        info.driver_version = self.device.driver_version
        info.device_type = str(self.device.type)
        info.platform_name = self.platform.name
        info.platform_vendor = self.platform.vendor
        
        # Compute resources - 添加安全检查
        info.max_compute_units = max(1, self.device.max_compute_units)
        info.max_work_group_size = max(1, self.device.max_work_group_size)
        info.max_work_item_dimensions = max(1, self.device.max_work_item_dimensions)
        
        # Get max work item sizes for each dimension
        max_sizes = []
        for i in range(info.max_work_item_dimensions):
            max_sizes.append(max(1, self.device.max_work_item_sizes[i]))
        info.max_work_item_sizes = max_sizes
        
        # Vector widths - 确保至少为1
        info.preferred_vector_width_char = max(1, self.device.preferred_vector_width_char)
        info.preferred_vector_width_short = max(1, self.device.preferred_vector_width_short)
        info.preferred_vector_width_int = max(1, self.device.preferred_vector_width_int)
        info.preferred_vector_width_long = max(1, self.device.preferred_vector_width_long)
        info.preferred_vector_width_float = max(1, self.device.preferred_vector_width_float)
        info.preferred_vector_width_double = max(1, self.device.preferred_vector_width_double)
        info.native_vector_width_char = max(1, self.device.native_vector_width_char)
        info.native_vector_width_short = max(1, self.device.native_vector_width_short)
        info.native_vector_width_int = max(1, self.device.native_vector_width_int)
        info.native_vector_width_long = max(1, self.device.native_vector_width_long)
        info.native_vector_width_float = max(1, self.device.native_vector_width_float)
        info.native_vector_width_double = max(1, self.device.native_vector_width_double)
        
        # Work group size multiple - 确保至少为1
        try:
            info.preferred_work_group_size_multiple = max(1, self.device.preferred_work_group_size_multiple)
        except:
            info.preferred_work_group_size_multiple = 1
            self._print("Preferred work group size multiple not available, using 1", "WARN")
        
        # Memory architecture - 添加最小安全值
        info.global_mem_size = max(100 * 1024 * 1024, self.device.global_mem_size)  # 至少100MB
        info.global_mem_cache_size = max(0, self.device.global_mem_cache_size)
        info.global_mem_cacheline_size = max(64, self.device.global_mem_cacheline_size)  # 至少64字节
        info.local_mem_size = max(1024, self.device.local_mem_size)  # 至少1KB
        info.local_mem_type = str(self.device.local_mem_type)
        info.constant_buffer_size = max(1024, self.device.max_constant_buffer_size)  # 至少1KB
        info.max_mem_alloc_size = max(10 * 1024 * 1024, self.device.max_mem_alloc_size)  # 至少10MB
        info.max_parameter_size = max(1024, self.device.max_parameter_size)  # 至少1KB
        
        # Clock and frequency - 确保合理值
        info.max_clock_frequency = max(100, self.device.max_clock_frequency)  # 至少100MHz
        info.profiling_timer_resolution = max(1, self.device.profiling_timer_resolution)
        
        # Extension support
        info.extensions = self.device.extensions.strip().split()
        
        # Check precision support
        info.fp16_support = 'cl_khr_fp16' in info.extensions
        info.fp64_support = 'cl_khr_fp64' in info.extensions or 'cl_amd_fp64' in info.extensions
        
        # Check 64-bit integer support
        info.int64_support = 'cl_khr_int64' in info.extensions
        
        # Execution capabilities
        cmd_queue_props = []
        props = self.device.queue_properties
        if props & cl.command_queue_properties.OUT_OF_ORDER_EXEC_MODE_ENABLE:
            cmd_queue_props.append("OUT_OF_ORDER_EXEC_MODE_ENABLE")
        if props & cl.command_queue_properties.PROFILING_ENABLE:
            cmd_queue_props.append("PROFILING_ENABLE")
        info.command_queue_properties = cmd_queue_props
        
        info.error_correction_support = self.device.error_correction_support
        info.endian_little = self.device.endian_little
        info.available = self.device.available
        info.compiler_available = self.device.compiler_available
        info.linker_available = self.device.linker_available
        
        # Check unified memory
        try:
            unified = self.device.host_unified_memory
            info.unified_memory = unified
        except:
            info.unified_memory = False
        
        self.report.device_info = info
        return info
    
    def test_precision_support(self) -> Dict[str, bool]:
        """Test various numerical precision support"""
        self._print("Testing numerical precision support...")
        
        precision_support = {}
        
        # Basic precision support
        precision_support["fp16"] = self.report.device_info.fp16_support
        precision_support["fp32"] = True  # All OpenCL devices support fp32
        precision_support["fp64"] = self.report.device_info.fp64_support
        
        # Integer precision support
        precision_support["int8"] = True  # Usually supported
        precision_support["int16"] = True
        precision_support["int32"] = True
        precision_support["int64"] = self.report.device_info.int64_support
        
        # Vector type support
        extensions = self.report.device_info.extensions
        precision_support["float3"] = True
        precision_support["float4"] = True
        precision_support["float8"] = True
        precision_support["float16"] = True
        
        # Check double precision vector support
        if precision_support["fp64"]:
            precision_support["double2"] = True
            precision_support["double4"] = True
            precision_support["double8"] = True
            precision_support["double16"] = True
        else:
            precision_support["double2"] = False
            precision_support["double4"] = False
            precision_support["double8"] = False
            precision_support["double16"] = False
        
        # Special extensions
        precision_support["half"] = precision_support["fp16"]
        precision_support["cl_amd_media_ops"] = 'cl_amd_media_ops' in extensions
        precision_support["cl_amd_media_ops2"] = 'cl_amd_media_ops2' in extensions
        
        self.report.precision_support = precision_support
        return precision_support
    
    def test_memory_bandwidth(self, test_sizes: List[int] = None) -> List[BandwidthResult]:
        """
        Test memory bandwidth
        
        Args:
            test_sizes: List of test data sizes (bytes)
        """
        self._print("Testing memory bandwidth...")
        
        if test_sizes is None:
            # Default test sizes: 1KB, 1MB, 10MB, 100MB
            test_sizes = [1024, 1024*1024, 10*1024*1024, 100*1024*1024]
            # Adjust test sizes to not exceed half of device max allocation memory
            max_size = self.report.device_info.max_mem_alloc_size // 2
            test_sizes = [size for size in test_sizes if size <= max_size]
            if not test_sizes:
                test_sizes = [max_size // 4]  # Use 1/4 of max allocation memory
        
        results = []
        
        # Test 1: Host to device transfer bandwidth
        for size in test_sizes:
            self._print(f"Testing H2D bandwidth with {size/1024/1024:.2f} MB data...")
            
            # Prepare test data
            host_data = np.random.rand(size // 4).astype(np.float32)  # 4 bytes per element
            
            # Warmup
            for _ in range(2):
                dev_data = cl_array.to_device(self.queue, host_data[:100])
                self.queue.finish()
            
            # Actual test
            start_time = time.perf_counter()
            
            try:
                dev_data = cl_array.to_device(self.queue, host_data)
                self.queue.finish()
            except Exception as e:
                self._print(f"  Error: {e}", "WARN")
                continue
            
            end_time = time.perf_counter()
            transfer_time = end_time - start_time
            
            # Calculate bandwidth (GB/s)
            bandwidth = (size / (1024**3)) / transfer_time
            
            results.append(BandwidthResult(
                test_name="Host to Device",
                transfer_size_bytes=size,
                transfer_time_ms=transfer_time * 1000,
                bandwidth_gbs=bandwidth,
                operations_per_second=1.0 / transfer_time,
                notes=f"Data size: {size/1024/1024:.2f} MB"
            ))
        
        # Test 2: Device to host transfer bandwidth
        for size in test_sizes:
            self._print(f"Testing D2H bandwidth with {size/1024/1024:.2f} MB data...")
            
            # Prepare device data
            host_data = np.random.rand(size // 4).astype(np.float32)
            dev_data = cl_array.to_device(self.queue, host_data)
            self.queue.finish()
            
            # Warmup
            for _ in range(2):
                small_result = dev_data[:100].get()
            
            # Actual test
            start_time = time.perf_counter()
            
            try:
                result = dev_data.get()
                self.queue.finish()
            except Exception as e:
                self._print(f"  Error: {e}", "WARN")
                continue
            
            end_time = time.perf_counter()
            transfer_time = end_time - start_time
            
            # Verify data
            if not np.allclose(result, host_data, rtol=1e-5):
                self._print(f"  Warning: Data verification failed", "WARN")
            
            # Calculate bandwidth
            bandwidth = (size / (1024**3)) / transfer_time
            
            results.append(BandwidthResult(
                test_name="Device to Host",
                transfer_size_bytes=size,
                transfer_time_ms=transfer_time * 1000,
                bandwidth_gbs=bandwidth,
                operations_per_second=1.0 / transfer_time,
                notes=f"Data size: {size/1024/1024:.2f} MB"
            ))
        
        # Test 3: Device internal copy bandwidth
        for size in test_sizes[:2]:  # Only test smaller two sizes
            self._print(f"Testing Device Copy bandwidth with {size/1024/1024:.2f} MB data...")
            
            # Create kernel for device internal copy
            kernel_code = """
            __kernel void copy_buffer(__global float* src, __global float* dst, int n) {
                int idx = get_global_id(0);
                if (idx < n) {
                    dst[idx] = src[idx];
                }
            }
            """
            
            # Prepare data
            n_elements = size // 4
            host_src = np.random.rand(n_elements).astype(np.float32)
            
            # Create buffers
            mf = cl.mem_flags
            src_buf = cl.Buffer(self.context, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=host_src)
            dst_buf = cl.Buffer(self.context, mf.WRITE_ONLY, size=size)
            
            # Compile kernel
            program = cl.Program(self.context, kernel_code).build()
            kernel = program.copy_buffer
            
            # Set work group size
            max_wg = self.report.device_info.max_work_group_size
            local_size = min(256, max_wg, n_elements)
            global_size = ((n_elements + local_size - 1) // local_size) * local_size
            
            # Warmup
            for _ in range(2):
                kernel(self.queue, (global_size,), (local_size,), src_buf, dst_buf, np.int32(n_elements))
                self.queue.finish()
            
            # Actual test
            start_time = time.perf_counter()
            
            # Execute multiple copies for more accurate timing
            iterations = 10
            for _ in range(iterations):
                kernel(self.queue, (global_size,), (local_size,), src_buf, dst_buf, np.int32(n_elements))
            self.queue.finish()
            
            end_time = time.perf_counter()
            total_time = end_time - start_time
            avg_time = total_time / iterations
            
            # Calculate bandwidth (consider each iteration copies data)
            bandwidth = (size / (1024**3)) / avg_time
            
            results.append(BandwidthResult(
                test_name="Device Copy",
                transfer_size_bytes=size,
                transfer_time_ms=avg_time * 1000,
                bandwidth_gbs=bandwidth,
                operations_per_second=1.0 / avg_time,
                notes=f"Data size: {size/1024/1024:.2f} MB, Iterations: {iterations}"
            ))
        
        self.report.bandwidth_results = results
        return results
    
    def test_constraints(self) -> List[ConstraintTest]:
        """Test various constraints and limits"""
        self._print("Testing device constraints...")
        
        tests = []
        info = self.report.device_info
        
        # Test 1: Max work group size
        test = ConstraintTest(
            test_name="Max Work Group Size",
            parameter_name="max_work_group_size",
            max_value=info.max_work_group_size,
            optimal_value=min(256, info.max_work_group_size),
            passed=info.max_work_group_size >= 1,
            notes=f"Recommended work group size: {min(256, info.max_work_group_size)}"
        )
        tests.append(test)
        
        # Test 2: Local memory size
        test = ConstraintTest(
            test_name="Local Memory Size",
            parameter_name="local_mem_size",
            max_value=info.local_mem_size,
            optimal_value=info.local_mem_size // 2,
            passed=info.local_mem_size > 0,
            notes=f"Type: {info.local_mem_type}"
        )
        tests.append(test)
        
        # Test 3: Global memory size
        global_mem_gb = info.global_mem_size / (1024**3)
        test = ConstraintTest(
            test_name="Global Memory Size",
            parameter_name="global_mem_size",
            max_value=info.global_mem_size,
            optimal_value=int(info.global_mem_size * 0.8),  # 80% of total
            passed=info.global_mem_size > 100 * 1024 * 1024,  # At least 100MB
            notes=f"Size: {global_mem_gb:.2f} GB"
        )
        tests.append(test)
        
        # Test 4: Max memory allocation
        max_alloc_gb = info.max_mem_alloc_size / (1024**3)
        test = ConstraintTest(
            test_name="Max Memory Allocation",
            parameter_name="max_mem_alloc_size",
            max_value=info.max_mem_alloc_size,
            optimal_value=info.max_mem_alloc_size // 2,
            passed=info.max_mem_alloc_size > 10 * 1024 * 1024,  # At least 10MB
            notes=f"Max single allocation: {max_alloc_gb:.2f} GB"
        )
        tests.append(test)
        
        # Test 5: Constant buffer size
        const_buf_mb = info.constant_buffer_size / (1024**2)
        test = ConstraintTest(
            test_name="Constant Buffer Size",
            parameter_name="constant_buffer_size",
            max_value=info.constant_buffer_size,
            optimal_value=info.constant_buffer_size // 2,
            passed=info.constant_buffer_size > 64 * 1024,  # At least 64KB
            notes=f"Size: {const_buf_mb:.2f} MB"
        )
        tests.append(test)
        
        # Test 6: Max parameter size
        max_param_kb = info.max_parameter_size / 1024
        test = ConstraintTest(
            test_name="Max Parameter Size",
            parameter_name="max_parameter_size",
            max_value=info.max_parameter_size,
            optimal_value=info.max_parameter_size // 2,
            passed=info.max_parameter_size > 1024,  # At least 1KB
            notes=f"Size: {max_param_kb:.2f} KB"
        )
        tests.append(test)
        
        # Test 7: Compute units
        test = ConstraintTest(
            test_name="Compute Units",
            parameter_name="max_compute_units",
            max_value=info.max_compute_units,
            optimal_value=info.max_compute_units,
            passed=info.max_compute_units > 0,
            notes=f"Number of compute units: {info.max_compute_units}"
        )
        tests.append(test)
        
        # Test 8: Clock frequency
        test = ConstraintTest(
            test_name="Clock Frequency",
            parameter_name="max_clock_frequency",
            max_value=info.max_clock_frequency,
            optimal_value=info.max_clock_frequency,
            passed=info.max_clock_frequency > 0,
            notes=f"Frequency: {info.max_clock_frequency} MHz"
        )
        tests.append(test)
        
        # Test 9: Global memory cache
        cache_mb = info.global_mem_cache_size / (1024**2)
        test = ConstraintTest(
            test_name="Global Memory Cache",
            parameter_name="global_mem_cache_size",
            max_value=info.global_mem_cache_size,
            optimal_value=info.global_mem_cache_size,
            passed=info.global_mem_cache_size > 0,
            notes=f"Cache size: {cache_mb:.2f} MB, Cacheline: {info.global_mem_cacheline_size} bytes"
        )
        tests.append(test)
        
        self.report.constraint_tests = tests
        return tests
    
    def generate_recommendations(self) -> Dict[str, Any]:
        """Generate recommended settings based on test results"""
        self._print("Generating optimization recommendations...")
        
        info = self.report.device_info
        recommendations = {}
        
        # Work group size recommendations
        max_wg = info.max_work_group_size
        pref_multiple = info.preferred_work_group_size_multiple
        
        # Determine optimal work group size
        if pref_multiple > 0:
            optimal_wg = pref_multiple
        else:
            # Recommend based on common architectures
            if "NVIDIA" in info.vendor:
                optimal_wg = 256  # NVIDIA GPUs usually 256 or 512
            elif "AMD" in info.vendor:
                optimal_wg = 256  # AMD GPUs usually 256
            elif "Intel" in info.vendor:
                optimal_wg = 32   # Intel integrated graphics usually smaller
            else:
                optimal_wg = min(256, max_wg)
        
        # Ensure not exceeding maximum
        optimal_wg = min(optimal_wg, max_wg)
        
        recommendations["work_group_size"] = {
            "max": max_wg,
            "optimal": optimal_wg,
            "preferred_multiple": pref_multiple,
            "suggestions": [
                f"Use {optimal_wg} as default work group size",
                f"Work group size should be multiple of {pref_multiple} (if available)"
            ]
        }
        
        # Memory usage recommendations
        global_mem_gb = info.global_mem_size / (1024**3)
        max_alloc_gb = info.max_mem_alloc_size / (1024**3)
        
        # Recommend max memory usage (70% of total memory)
        safe_usage = int(info.global_mem_size * 0.7)
        safe_usage_gb = safe_usage / (1024**3)
        
        recommendations["memory_usage"] = {
            "total_memory_gb": round(global_mem_gb, 2),
            "max_allocation_gb": round(max_alloc_gb, 2),
            "safe_usage_gb": round(safe_usage_gb, 2),
            "safe_usage_bytes": safe_usage,
            "suggestions": [
                f"Single allocation should not exceed {max_alloc_gb:.2f} GB",
                f"Total memory usage recommended not to exceed {safe_usage_gb:.2f} GB"
            ]
        }
        
        # Local memory usage recommendations
        local_mem_kb = info.local_mem_size / 1024
        safe_local = int(info.local_mem_size * 0.8)  # 80% of local memory
        
        recommendations["local_memory"] = {
            "total_kb": round(local_mem_kb, 2),
            "type": info.local_mem_type,
            "safe_usage_bytes": safe_local,
            "suggestions": [
                f"Local memory type: {info.local_mem_type}",
                f"Each work group recommended to use no more than {safe_local} bytes of local memory"
            ]
        }
        
        # Precision recommendations
        recommendations["precision"] = {
            "fp16_available": info.fp16_support,
            "fp64_available": info.fp64_support,
            "recommended_precision": "fp32",  # Default recommendation
            "suggestions": []
        }
        
        if info.fp16_support:
            recommendations["precision"]["suggestions"].append(
                "FP16 available: Suitable for memory or bandwidth constrained computations"
            )
        
        if info.fp64_support:
            recommendations["precision"]["suggestions"].append(
                "FP64 available: Suitable for scientific computing requiring high precision"
            )
        
        # Architecture specific optimizations
        vendor_specific = {}
        
        if "NVIDIA" in info.vendor:
            vendor_specific["vendor"] = "NVIDIA"
            vendor_specific["suggestions"] = [
                "Consider using CUDA for NVIDIA specific optimizations",
                "NVIDIA GPUs usually have high single precision performance"
            ]
        elif "AMD" in info.vendor:
            vendor_specific["vendor"] = "AMD"
            vendor_specific["suggestions"] = [
                "AMD GPUs usually have high memory bandwidth",
                "Consider using ROCm for AMD specific optimizations"
            ]
        elif "Intel" in info.vendor:
            vendor_specific["vendor"] = "Intel"
            vendor_specific["suggestions"] = [
                "Intel integrated graphics usually have smaller work group sizes",
                "May need more conservative memory usage strategies"
            ]
        
        recommendations["vendor_specific"] = vendor_specific
        
        # Performance optimization suggestions
        performance_tips = []
        
        # Add suggestions based on bandwidth test results
        if self.report.bandwidth_results:
            h2d_results = [r for r in self.report.bandwidth_results if r.test_name == "Host to Device"]
            if h2d_results:
                avg_bandwidth = np.mean([r.bandwidth_gbs for r in h2d_results])
                if avg_bandwidth < 5.0:
                    performance_tips.append(f"Host to device bandwidth is low ({avg_bandwidth:.2f} GB/s), consider reducing data transfer frequency")
        
        # Add suggestions based on constraint tests
        constraint_failures = [t for t in self.report.constraint_tests if not t.passed]
        if constraint_failures:
            for test in constraint_failures[:3]:  # Only show first 3
                performance_tips.append(f"Note constraint: {test.test_name} ({test.notes})")
        
        recommendations["performance_tips"] = performance_tips
        
        # Kernel optimization parameters
        recommendations["kernel_optimization"] = {
            "vectorization": {
                "float_vector_width": info.preferred_vector_width_float,
                "double_vector_width": info.preferred_vector_width_double,
                "suggestion": f"Consider using float{info.preferred_vector_width_float} vectorized operations"
            },
            "compiler_flags": [
                "-cl-fast-relaxed-math",
                "-cl-mad-enable",
                "-cl-no-signed-zeros"
            ]
        }
        
        self.report.recommended_settings = recommendations
        return recommendations
    
    def generate_batch_configuration(self, 
                                   output_file: Optional[str] = None,
                                   config_name: str = "auto_generated_gpu_config.yml") -> Dict[str, Any]:
        """
        Generate optimized batch test configuration based on device capabilities
        
        Args:
            output_file: Path to save the configuration file
            config_name: Name of the configuration
            
        Returns:
            Dictionary containing the generated configuration
        """
        if not self.report.device_info:
            self.collect_device_info()
            self.test_precision_support()
            self.test_constraints()
        
        self._print("Generating optimized batch test configuration...")
        
        # Calculate device capability scores
        capability_scores = self._calculate_capability_scores()
        
        # Generate configurations for each benchmark type
        test_configs = []
        
        # 1. Trajectory integral configuration
        traj_config = self._generate_trajectory_config(capability_scores)
        if traj_config:
            test_configs.append(traj_config)
        
        # 2. Monte Carlo configuration
        mc_config = self._generate_monte_carlo_config(capability_scores)
        if mc_config:
            test_configs.append(mc_config)
        
        # 3. N-body simulation configuration
        nbody_config = self._generate_nbody_config(capability_scores)
        if nbody_config:
            test_configs.append(nbody_config)
        
        # Build full batch configuration
        batch_config = self._build_batch_configuration(test_configs, config_name)
        
        # Create summary
        summary = {
            "total_tests": len(test_configs),
            "total_estimated_runtime": sum(c.estimated_runtime for c in test_configs),
            "average_confidence": np.mean([c.confidence_level for c in test_configs]),
            "average_safety": np.mean([c.safety_factor for c in test_configs]),
            "recommended_precisions": list(set(c.precision for c in test_configs)),
        }
        
        # Create auto-generated config object
        auto_config = AutoGeneratedConfig(
            device_info=asdict(self.report.device_info),
            generation_timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
            generation_parameters=self.config_params,
            test_configurations=[asdict(c) for c in test_configs],
            batch_config=batch_config,
            summary=summary
        )
        
        # Save to file if requested
        if output_file and YAML_AVAILABLE:
            self._save_configuration(auto_config, output_file)
        
        # Print configuration summary
        self._print_configuration_summary(auto_config)
        
        return batch_config
    
    def _calculate_capability_scores(self) -> Dict[str, float]:
        """Calculate capability scores for different aspects"""
        info = self.report.device_info
        
        # Memory capability score (0-1)
        # 修复：检查全局内存大小是否为0
        if info.global_mem_size <= 0:
            # 如果全局内存大小为0，使用默认值4GB
            self._print("Warning: global_mem_size is 0 or negative, using default 4GB for memory score", "WARN")
            mem_score = 0.5  # 中等内存评分
        else:
            mem_score = min(1.0, info.global_mem_size / (4 * 1024**3))  # Normalize to 4GB
        
        # Compute capability score
        compute_units = max(1, info.max_compute_units)  # 确保至少为1
        clock_freq = max(100, info.max_clock_frequency)  # 确保至少为100MHz
        compute_score = min(1.0, (compute_units * clock_freq) / (2048 * 1000))  # Normalize to 2048 CUs at 1GHz
        
        # Bandwidth score (if available)
        bw_score = 0.5  # Default
        if self.report.bandwidth_results:
            h2d_speeds = [r.bandwidth_gbs for r in self.report.bandwidth_results if "Host to Device" in r.test_name]
            if h2d_speeds:
                avg_bw = np.mean(h2d_speeds)
                bw_score = min(1.0, avg_bw / 50.0)  # Normalize to 50 GB/s
        
        # Vectorization score
        vec_widths = [
            max(1, info.preferred_vector_width_float),  # 确保至少为1
            max(1, info.preferred_vector_width_double),
        ]
        vec_score = min(1.0, np.mean(vec_widths) / 4.0)  # Normalize to vector width 4
        
        # Precision support score
        precision_scores = {
            "fp16": 0.3 if info.fp16_support else 0.0,
            "fp32": 1.0,  # Always supported
            "fp64": 0.5 if info.fp64_support else 0.0,
        }
        
        return {
            "memory": mem_score,
            "compute": compute_score,
            "bandwidth": bw_score,
            "vectorization": vec_score,
            "precisions": precision_scores,
            "overall": (mem_score * 0.3 + compute_score * 0.4 + bw_score * 0.2 + vec_score * 0.1),
        }
    
    def _generate_trajectory_config(self, scores: Dict[str, float]) -> Optional[TestConfiguration]:
        """Generate configuration for trajectory integral benchmark"""
        info = self.report.device_info
        
        # Determine precision based on device support
        precision = "fp32"  # Default
        if scores["precisions"]["fp64"] > 0.5:
            precision = "fp64"
        
        # Calculate parameters based on capability scores
        compute_score = scores["compute"]
        mem_score = scores["memory"]
        
        # Base parameters (for score = 0.5)
        base_steps = 5000
        base_paths = 500
        
        # Scale parameters based on capability
        scale_factor = compute_score * 2.0  # 0-2 range
        steps = int(base_steps * scale_factor)
        paths = int(base_paths * scale_factor)
        
        # Apply memory constraints
        # Estimated memory usage: positions (paths * 4 * precision_size)
        precision_size = 4 if precision == "fp32" else 8
        estimated_memory = paths * 4 * precision_size  # bytes
        max_memory = info.global_mem_size * self.config_params["memory_safety_factor"]
        
        # 修复：检查 max_memory 是否为0
        if max_memory <= 0:
            # 如果最大内存为0或负数，使用最小安全值
            max_memory = 100 * 1024 * 1024  # 100 MB 作为最小安全值
            self._print(f"  Warning: max_memory is 0 or negative, using {max_memory/1024/1024:.0f} MB as minimum", "WARN")
        
        if estimated_memory > max_memory:
            # Reduce paths to fit in memory
            paths = int(max_memory / (4 * precision_size))
            self._print(f"  Reduced trajectory paths to {paths} due to memory constraints", "WARN")
        
        # Ensure reasonable minimums
        steps = max(1000, steps)
        paths = max(100, paths)
        
        # Limit maximums for reasonable runtime
        steps = min(50000, steps)
        paths = min(5000, paths)
        
        # Estimate runtime (very rough estimation)
        # Assuming each path-step takes about 100 operations
        total_ops = steps * paths * 100
        # Very rough ops/sec estimation based on compute units and frequency
        ops_per_sec = info.max_compute_units * info.max_clock_frequency * 1e6 * 0.1  # 10% efficiency
        estimated_runtime = total_ops / ops_per_sec if ops_per_sec > 0 else 30.0
        
        # Adjust to target runtime
        target_runtime = self.config_params["target_runtime_per_test"]
        if estimated_runtime > target_runtime * 2:
            # Reduce scale
            reduction = (target_runtime * 2) / estimated_runtime
            steps = int(steps * math.sqrt(reduction))  # sqrt to balance steps and paths
            paths = int(paths * math.sqrt(reduction))
        
        # Calculate confidence and safety
        confidence = min(1.0, compute_score * 0.8 + mem_score * 0.2)
        
        # 修复：避免除零错误
        if max_memory <= 0:
            safety = 0.0
        else:
            safety = min(1.0, 1.0 - (estimated_memory / max_memory))
        
        config = TestConfiguration(
            benchmark_type="trajectory",
            precision=precision,
            recommended_params={
                "steps": steps,
                "paths": paths,
                "iterations": self._calculate_iterations(confidence),
                "warmup": self.config_params["warmup_iterations"],
            },
            estimated_runtime=estimated_runtime,
            confidence_level=confidence,
            safety_factor=safety,
            notes=f"Based on compute score: {compute_score:.2f}, memory score: {mem_score:.2f}"
        )
        
        return config
    
    def _generate_monte_carlo_config(self, scores: Dict[str, float]) -> Optional[TestConfiguration]:
        """Generate configuration for Monte Carlo benchmark"""
        info = self.report.device_info
        
        # Determine precision
        precision = "fp32"
        if scores["precisions"]["fp64"] > 0.5:
            precision = "fp64"
        
        # Monte Carlo is compute-bound, use compute score
        compute_score = scores["compute"]
        bw_score = scores["bandwidth"]
        
        # Base samples for score = 0.5
        base_samples = 5_000_000
        
        # Scale based on capability
        scale_factor = compute_score * 2.0
        samples = int(base_samples * scale_factor)
        
        # Apply vectorization optimization
        vec_score = scores["vectorization"]
        if vec_score > 0.5:
            # Round to nearest multiple of 4 for better vectorization
            samples = ((samples + 3) // 4) * 4
        
        # Memory usage is minimal, but check anyway
        precision_size = 4 if precision == "fp32" else 8
        estimated_memory = samples * 2 * precision_size  # x and y coordinates
        max_memory = info.global_mem_size * self.config_params["memory_safety_factor"]
        
        if estimated_memory > max_memory:
            samples = int(max_memory / (2 * precision_size))
            self._print(f"  Reduced Monte Carlo samples to {samples} due to memory constraints", "WARN")
        
        # Ensure reasonable bounds
        samples = max(1_000_000, samples)
        samples = min(100_000_000, samples)
        
        # Estimate runtime
        # Each sample: random number generation (2 values) + multiplication + addition + comparison
        total_ops = samples * 10  # ~10 ops per sample
        # Very rough ops/sec estimation based on compute units and frequency
        ops_per_sec = info.max_compute_units * info.max_clock_frequency * 1e6 * 0.15  # 15% efficiency
        estimated_runtime = total_ops / ops_per_sec if ops_per_sec > 0 else 20.0
        
        # Adjust to target runtime
        target_runtime = self.config_params["target_runtime_per_test"]
        if estimated_runtime > target_runtime * 2:
            reduction = (target_runtime * 2) / estimated_runtime
            samples = int(samples * reduction)
        
        # Calculate confidence and safety
        confidence = min(1.0, compute_score * 0.7 + bw_score * 0.3)
        safety = min(1.0, 1.0 - (estimated_memory / max_memory))
        
        # Determine batching strategy
        if samples > 10_000_000:
            batches = max(2, samples // 5_000_000)
            samples_per_batch = samples // batches
        else:
            batches = 1
            samples_per_batch = samples
        
        config = TestConfiguration(
            benchmark_type="monte_carlo",
            precision=precision,
            recommended_params={
                "samples": samples,
                "batches": batches,
                "samples_per_batch": samples_per_batch,
                "iterations": self._calculate_iterations(confidence),
                "warmup": self.config_params["warmup_iterations"],
            },
            estimated_runtime=estimated_runtime,
            confidence_level=confidence,
            safety_factor=safety,
            notes=f"Using {batches} batch(es) for memory efficiency"
        )
        
        return config
    
    def _generate_nbody_config(self, scores: Dict[str, float]) -> Optional[TestConfiguration]:
        """Generate configuration for N-body simulation benchmark"""
        info = self.report.device_info
        
        # Determine precision
        precision = "fp32"
        if scores["precisions"]["fp64"] > 0.5:
            precision = "fp64"
        
        compute_score = scores["compute"]
        mem_score = scores["memory"]
        
        # N-body is O(N²) complexity, be conservative
        # Base parameters for score = 0.5
        base_bodies = 500
        base_steps = 50
        
        # Scale based on capability (square root since complexity is O(N²))
        scale_factor = math.sqrt(compute_score * 2.0)
        bodies = int(base_bodies * scale_factor)
        steps = int(base_steps * scale_factor)
        
        # Apply memory constraints
        # Memory per body: position (4 floats), velocity (4 floats), mass (1 float)
        precision_size = 4 if precision == "fp32" else 8
        bytes_per_body = (4 + 4 + 1) * precision_size
        estimated_memory = bodies * bytes_per_body
        max_memory = info.global_mem_size * self.config_params["memory_safety_factor"]
        
        if estimated_memory > max_memory:
            bodies = int(max_memory / bytes_per_body)
            self._print(f"  Reduced N-body particles to {bodies} due to memory constraints", "WARN")
        
        # Ensure reasonable bounds
        bodies = max(100, bodies)
        bodies = min(5000, bodies)
        steps = max(20, steps)
        steps = min(200, steps)
        
        # Determine tile mode based on local memory
        local_mem_available = info.local_mem_size
        tile_mode = False
        if local_mem_available > 16 * 1024:  # At least 16KB local memory
            # Check if we can use tile mode
            # For tile mode, need local memory for tile_size * (position + mass)
            tile_size = min(128, bodies, int(math.sqrt(local_mem_available / (bytes_per_body / 2))))
            if tile_size >= 32:  # Need reasonable tile size
                tile_mode = True
        
        # Estimate runtime (O(N²) complexity)
        total_ops = bodies * bodies * steps * 20  # ~20 ops per interaction per step
        ops_per_sec = info.max_compute_units * info.max_clock_frequency * 1e6 * 0.05  # 5% efficiency for O(N²)
        estimated_runtime = total_ops / ops_per_sec if ops_per_sec > 0 else 25.0
        
        # Adjust to target runtime
        target_runtime = self.config_params["target_runtime_per_test"]
        if estimated_runtime > target_runtime * 2:
            # Reduce both bodies and steps
            reduction = math.sqrt((target_runtime * 2) / estimated_runtime)
            bodies = int(bodies * reduction)
            steps = int(steps * reduction)
        
        # Calculate confidence and safety
        confidence = min(1.0, compute_score * 0.4 + mem_score * 0.6)
        safety = min(1.0, 1.0 - (estimated_memory / max_memory))
        
        # Determine chunk size for stability
        chunk_size = 5
        if bodies > 1000:
            chunk_size = 3
        if bodies > 2000:
            chunk_size = 2
        
        config = TestConfiguration(
            benchmark_type="nbody",
            precision=precision,
            recommended_params={
                "bodies": bodies,
                "steps": steps,
                "dt": 0.01,
                "chunk_size": chunk_size,
                "tile_mode": tile_mode,
                "iterations": self._calculate_iterations(confidence),
                "warmup": self.config_params["warmup_iterations"],
            },
            estimated_runtime=estimated_runtime,
            confidence_level=confidence,
            safety_factor=safety,
            notes=f"Tile mode: {'enabled' if tile_mode else 'disabled'} (local memory: {local_mem_available/1024:.1f}KB)"
        )
        
        return config
    
    def _calculate_iterations(self, confidence: float) -> int:
        """Calculate number of iterations based on confidence level"""
        min_iter = self.config_params["min_test_iterations"]
        max_iter = self.config_params["max_test_iterations"]
        
        # Higher confidence -> fewer iterations needed
        iterations = int(min_iter + (max_iter - min_iter) * (1.0 - confidence))
        
        # Ensure odd number for better median calculation
        if iterations % 2 == 0:
            iterations += 1
        
        return max(min_iter, min(max_iter, iterations))
    
    def _build_batch_configuration(self, test_configs: List[TestConfiguration], 
                                 config_name: str) -> Dict[str, Any]:
        """Build complete batch.py configuration from test configurations"""
        
        jobs = []
        plot_groups = []
        
        for i, config in enumerate(test_configs):
            job_name = f"auto_{config.benchmark_type}_{config.precision}"
            
            if config.benchmark_type == "trajectory":
                job = self._create_trajectory_job(job_name, config)
                plot_group = self._create_trajectory_plot_group(job_name, config)
                
            elif config.benchmark_type == "monte_carlo":
                job = self._create_monte_carlo_job(job_name, config)
                plot_group = self._create_monte_carlo_plot_group(job_name, config)
                
            elif config.benchmark_type == "nbody":
                job = self._create_nbody_job(job_name, config)
                plot_group = self._create_nbody_plot_group(job_name, config)
            else:
                continue
            
            jobs.append(job)
            plot_groups.append(plot_group)
        
        # Create batch configuration
        batch_config = {
            "settings": {
                "output_dir": f"batch_results/auto_{int(time.time())}",
                "plots_dir": f"plots/auto_{int(time.time())}",
                "unified_output": "auto_generated_results.json",
                "sleep_interval": 1.0,
            },
            "jobs": jobs,
            "plot_groups": plot_groups,
            "metadata": {
                "generated_by": "gpu_base_cl.py",
                "generation_timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                "config_name": config_name,
                "device_name": self.report.device_info.name,
                "confidence_threshold": self.config_params["confidence_threshold"],
                "safety_threshold": self.config_params["safety_threshold"],
            }
        }
        
        return batch_config
    
    def _create_trajectory_job(self, name: str, config: TestConfiguration) -> Dict[str, Any]:
        """Create trajectory job configuration"""
        params = config.recommended_params
        
        job = {
            "name": name,
            "tool": "gpu_traj_cl.py",
            "task": "trajectory",
            "scale_type": "trajectory",
            "base_args": [
                "--precision", config.precision,
                "--repeats", str(params["iterations"]),
                "--warmup", str(params["warmup"]),
                "--platform", "0",
                "--device", "0",
                "--size", f"({params['steps']},{params['paths']})",
            ]
        }
        
        return job
    
    def _create_monte_carlo_job(self, name: str, config: TestConfiguration) -> Dict[str, Any]:
        """Create Monte Carlo job configuration"""
        params = config.recommended_params
        
        job = {
            "name": name,
            "tool": "gpu_mc_cl.py",
            "task": "monte_carlo",
            "scale_type": "monte_carlo",
            "base_args": [
                "--precision", config.precision,
                "--repeats", str(params["iterations"]),
                "--warmup", str(params["warmup"]),
                "--platform", "0",
                "--device", "0",
            ]
        }
        
        if params["batches"] > 1:
            job["base_args"].extend([
                "--batches", str(params["batches"]),
                "--samples-per-batch", str(params["samples_per_batch"])
            ])
        else:
            job["base_args"].extend(["--samples", str(params["samples"])])
        
        return job
    
    def _create_nbody_job(self, name: str, config: TestConfiguration) -> Dict[str, Any]:
        """Create N-body job configuration"""
        params = config.recommended_params
        
        job = {
            "name": name,
            "tool": "gpu_nbody_cl.py",
            "task": "nbody",
            "scale_type": "nbody",
            "base_args": [
                "--precision", config.precision,
                "--repeats", str(params["iterations"]),
                "--warmup", str(params["warmup"]),
                "--platform", "0",
                "--device", "0",
                "--bodies", str(params["bodies"]),
                "--steps", str(params["steps"]),
                "--dt", str(params["dt"]),
                "--chunk-size", str(params["chunk_size"]),
            ]
        }
        
        if not params["tile_mode"]:
            job["base_args"].append("--no-tile")
        
        return job
    
    def _create_trajectory_plot_group(self, job_name: str, config: TestConfiguration) -> Dict[str, Any]:
        """Create trajectory plot group"""
        return {
            "name": f"Auto: Trajectory ({config.precision.upper()})",
            "task": "Trajectory Integral (GPU)",
            "scale_type": "trajectory",
            "x_parameter": "steps",
            "x_label": "Integration Steps",
            "y_parameter": "avg_time",
            "y_label": "Average Execution Time (s)",
            "varied_params": {
                "steps": [
                    max(1000, config.recommended_params["steps"] // 4),
                    config.recommended_params["steps"] // 2,
                    config.recommended_params["steps"],
                    config.recommended_params["steps"] * 2,
                    min(50000, config.recommended_params["steps"] * 4),
                ]
            },
            "fixed_params": {
                "trajectories": config.recommended_params["paths"]
            },
            "jobs": [job_name]
        }
    
    def _create_monte_carlo_plot_group(self, job_name: str, config: TestConfiguration) -> Dict[str, Any]:
        """Create Monte Carlo plot group"""
        return {
            "name": f"Auto: Monte Carlo ({config.precision.upper()})",
            "task": "Monte Carlo Pi (GPU Batched)",
            "scale_type": "monte_carlo",
            "x_parameter": "samples",
            "x_label": "Number of Samples (millions)",
            "y_parameter": "samples_per_second",
            "y_label": "Samples per Second",
            "varied_params": {
                "samples": [
                    max(1000000, config.recommended_params["samples"] // 4),
                    config.recommended_params["samples"] // 2,
                    config.recommended_params["samples"],
                    min(100000000, config.recommended_params["samples"] * 2),
                    min(500000000, config.recommended_params["samples"] * 4),
                ]
            },
            "fixed_params": {},
            "jobs": [job_name]
        }
    
    def _create_nbody_plot_group(self, job_name: str, config: TestConfiguration) -> Dict[str, Any]:
        """Create N-body plot group"""
        return {
            "name": f"Auto: N-Body ({config.precision.upper()}, {'Tile' if config.recommended_params['tile_mode'] else 'No-Tile'})",
            "task": "N-Body Simulation (GPU)",
            "scale_type": "nbody",
            "x_parameter": "bodies",
            "x_label": "Number of Bodies",
            "y_parameter": "avg_time",
            "y_label": "Average Execution Time (s)",
            "varied_params": {
                "bodies": [
                    max(100, config.recommended_params["bodies"] // 4),
                    config.recommended_params["bodies"] // 2,
                    config.recommended_params["bodies"],
                    min(5000, config.recommended_params["bodies"] * 2),
                    min(10000, config.recommended_params["bodies"] * 4),
                ]
            },
            "fixed_params": {
                "steps": config.recommended_params["steps"],
                "dt": config.recommended_params["dt"]
            },
            "jobs": [job_name]
        }
    
    def _save_configuration(self, auto_config: AutoGeneratedConfig, output_file: str):
        """Save generated configuration to YAML file"""
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                yaml.dump(auto_config.batch_config, f, default_flow_style=False, allow_unicode=True)
            
            self._print(f"Configuration saved to {output_file}")
            
            # Also save detailed report
            report_file = output_file.replace('.yml', '_report.json').replace('.yaml', '_report.json')
            with open(report_file, 'w', encoding='utf-8') as f:
                json.dump(asdict(auto_config), f, indent=2, ensure_ascii=False)
            
            self._print(f"Detailed report saved to {report_file}")
            
        except Exception as e:
            self._print(f"Error saving configuration: {e}", "ERROR")
    
    def _print_configuration_summary(self, auto_config: AutoGeneratedConfig):
        """Print summary of generated configuration"""
        summary = auto_config.summary
        batch_config = auto_config.batch_config
        
        print("\n" + "="*80)
        print("AUTO-GENERATED GPU TEST CONFIGURATION SUMMARY")
        print("="*80)
        
        print(f"\nDevice: {auto_config.device_info['name']}")
        print(f"Vendor: {auto_config.device_info['vendor']}")
        print(f"Generated: {auto_config.generation_timestamp}")
        
        print(f"\nTotal Tests Generated: {summary['total_tests']}")
        print(f"Estimated Total Runtime: {summary['total_estimated_runtime']:.1f} seconds")
        print(f"Average Confidence Level: {summary['average_confidence']:.2f}")
        print(f"Average Safety Factor: {summary['average_safety']:.2f}")
        print(f"Recommended Precisions: {', '.join(summary['recommended_precisions'])}")
        
        print(f"\nGenerated Configuration Details:")
        print("-" * 60)
        
        for i, job in enumerate(batch_config.get("jobs", [])):
            print(f"\n{i+1}. {job['name']}")
            print(f"   Tool: {job['tool']}")
            print(f"   Args: {' '.join(job['base_args'])}")
        
        print(f"\nOutput Directory: {batch_config['settings']['output_dir']}")
        print(f"Plots Directory: {batch_config['settings']['plots_dir']}")
        
        print("\nTo use this configuration:")
        print(f"  python tools/bench/batch.py {batch_config['metadata']['config_name']}")
        
        print("\n" + "="*80)
    
    def run_all_tests(self):
        """Run all tests"""
        start_time = time.perf_counter()
        
        # Collect device information
        self.collect_device_info()
        
        # Test precision support
        self.test_precision_support()
        
        # Test constraints
        self.test_constraints()
        
        # Test bandwidth (using safe test sizes)
        max_test_size = min(100 * 1024 * 1024, self.report.device_info.max_mem_alloc_size // 4)
        if max_test_size > 1024:  # At least 1KB
            test_sizes = [
                1024,  # 1KB
                1024 * 1024,  # 1MB
                min(10 * 1024 * 1024, max_test_size),  # 10MB or smaller
                min(100 * 1024 * 1024, max_test_size)  # 100MB or smaller
            ]
            # Remove duplicates
            test_sizes = list(dict.fromkeys(test_sizes))
            self.test_memory_bandwidth(test_sizes)
        
        # Generate recommended settings
        self.generate_recommendations()
        
        end_time = time.perf_counter()
        self.report.test_duration_seconds = end_time - start_time
        
        return self.report
    
    def print_report(self, detailed: bool = True):
        """Print test report"""
        report = self.report
        
        print("\n" + "="*80)
        print("GPU OpenCL Capability Report")
        print("="*80)
        
        # Device basic information
        print(f"\n1. DEVICE INFORMATION")
        print(f"   Name: {report.device_info.name}")
        print(f"   Vendor: {report.device_info.vendor}")
        print(f"   Device Type: {report.device_info.device_type}")
        print(f"   OpenCL Version: {report.device_info.version}")
        print(f"   Driver Version: {report.device_info.driver_version}")
        print(f"   Platform: {report.device_info.platform_name}")
        
        # Compute resources
        print(f"\n2. COMPUTE RESOURCES")
        print(f"   Compute Units: {report.device_info.max_compute_units}")
        print(f"   Max Work Group Size: {report.device_info.max_work_group_size}")
        print(f"   Preferred Work Group Multiple: {report.device_info.preferred_work_group_size_multiple}")
        print(f"   Max Work Item Sizes: {report.device_info.max_work_item_sizes}")
        print(f"   Clock Frequency: {report.device_info.max_clock_frequency} MHz")
        
        # Memory architecture
        print(f"\n3. MEMORY ARCHITECTURE")
        print(f"   Global Memory: {report.device_info.global_mem_size / (1024**3):.2f} GB")
        print(f"   Max Allocation: {report.device_info.max_mem_alloc_size / (1024**3):.2f} GB")
        print(f"   Local Memory: {report.device_info.local_mem_size / 1024:.0f} KB ({report.device_info.local_mem_type})")
        print(f"   Constant Buffer: {report.device_info.constant_buffer_size / 1024:.0f} KB")
        print(f"   Cache Size: {report.device_info.global_mem_cache_size / 1024:.0f} KB")
        
        # Precision support
        print(f"\n4. PRECISION SUPPORT")
        precision = report.precision_support
        print(f"   FP16: {'✓' if precision.get('fp16', False) else '✗'}")
        print(f"   FP32: {'✓' if precision.get('fp32', False) else '✗'}")
        print(f"   FP64: {'✓' if precision.get('fp64', False) else '✗'}")
        print(f"   Int64: {'✓' if precision.get('int64', False) else '✗'}")
        
        if detailed:
            # Extensions (first 10)
            print(f"\n5. EXTENSIONS (first 10)")
            extensions = report.device_info.extensions
            for i, ext in enumerate(extensions[:10]):
                print(f"   {i+1:2d}. {ext}")
            if len(extensions) > 10:
                print(f"   ... and {len(extensions) - 10} more")
        
        # Bandwidth results
        if report.bandwidth_results:
            print(f"\n6. MEMORY BANDWIDTH")
            for result in report.bandwidth_results:
                print(f"   {result.test_name:20s}: {result.bandwidth_gbs:6.2f} GB/s "
                      f"({result.transfer_time_ms:.2f} ms for {result.transfer_size_bytes/1024/1024:.1f} MB)")
        
        # Constraint test results
        if report.constraint_tests:
            print(f"\n7. CONSTRAINTS")
            for test in report.constraint_tests:
                status = "✓" if test.passed else "✗"
                value_desc = f"{test.max_value:,}"
                if "memory" in test.test_name.lower():
                    # For memory sizes, convert to more friendly units
                    if test.max_value > 1024**3:  # GB
                        value_desc = f"{test.max_value/(1024**3):.1f} GB"
                    elif test.max_value > 1024**2:  # MB
                        value_desc = f"{test.max_value/(1024**2):.1f} MB"
                    elif test.max_value > 1024:  # KB
                        value_desc = f"{test.max_value/1024:.1f} KB"
                
                print(f"   {status} {test.test_name:25s}: {value_desc:15s} ({test.notes})")
        
        # Recommended settings
        if report.recommended_settings:
            print(f"\n8. RECOMMENDED SETTINGS")
            rec = report.recommended_settings
            
            # Work group
            wg = rec.get("work_group_size", {})
            print(f"   Work Group Size:")
            print(f"     Max: {wg.get('max', 'N/A')}")
            print(f"     Optimal: {wg.get('optimal', 'N/A')}")
            if wg.get('suggestions'):
                for suggestion in wg['suggestions']:
                    print(f"     • {suggestion}")
            
            # Memory
            mem = rec.get("memory_usage", {})
            print(f"   Memory Usage:")
            print(f"     Total: {mem.get('total_memory_gb', 'N/A')} GB")
            print(f"     Max Allocation: {mem.get('max_allocation_gb', 'N/A')} GB")
            print(f"     Safe Usage: {mem.get('safe_usage_gb', 'N/A')} GB")
            
            # Performance tips
            tips = rec.get("performance_tips", [])
            if tips:
                print(f"   Performance Tips:")
                for tip in tips[:5]:  # Only show first 5
                    print(f"     • {tip}")
        
        # Test metadata
        print(f"\n9. TEST METADATA")
        print(f"   Timestamp: {report.timestamp}")
        print(f"   Test Duration: {report.test_duration_seconds:.2f} seconds")
        
        print("\n" + "="*80)
    
    def save_report(self, filename: str):
        """Save report to JSON file"""
        report_dict = {
            "device_info": asdict(self.report.device_info),
            "precision_support": self.report.precision_support,
            "bandwidth_results": [asdict(r) for r in self.report.bandwidth_results],
            "constraint_tests": [asdict(t) for t in self.report.constraint_tests],
            "recommended_settings": self.report.recommended_settings,
            "timestamp": self.report.timestamp,
            "test_duration_seconds": self.report.test_duration_seconds
        }
        
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(report_dict, f, indent=2, ensure_ascii=False)
        
        self._print(f"Report saved to {filename}")


# Update the main function to include configuration generation
def main():
    """Main function"""
    parser = argparse.ArgumentParser(
        description="GPU OpenCL Capability Profiler with Auto Configuration",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                            # Auto detect default GPU
  %(prog)s --platform 0 --device 0    # Specify platform and device
  %(prog)s --output report.json       # Save report to JSON file
  %(prog)s --generate-config          # Generate optimized test configuration
  %(prog)s --config-output auto.yml   # Save generated configuration
  %(prog)s --detailed                 # Show detailed report
  %(prog)s --quiet                    # Quiet mode, only output final report
        """
    )
    
    parser.add_argument(
        "--platform", type=int, default=0,
        help="OpenCL platform index (default: 0)"
    )
    
    parser.add_argument(
        "--device", type=int, default=0,
        help="OpenCL device index (default: 0)"
    )
    
    parser.add_argument(
        "--output", type=str,
        help="Output JSON file path for the report"
    )
    
    parser.add_argument(
        "--generate-config", action="store_true",
        help="Generate optimized test configuration for batch.py"
    )
    
    parser.add_argument(
        "--config-output", type=str, default="auto_gpu_config.yml",
        help="Output file for generated configuration (default: auto_gpu_config.yml)"
    )
    
    parser.add_argument(
        "--detailed", action="store_true",
        help="Print detailed report including all extensions"
    )
    
    parser.add_argument(
        "--quiet", action="store_true",
        help="Quiet mode, minimize progress output"
    )
    
    parser.add_argument(
        "--test-sizes", type=str, default="1KB,1MB,10MB",
        help="Comma-separated list of test sizes (e.g., '1KB,1MB,10MB')"
    )
    
    args = parser.parse_args()
    
    if not PYOPENCL_AVAILABLE:
        print("Error: PyOpenCL not installed. Please install: pip install pyopencl")
        sys.exit(1)
    
    print("GPU OpenCL Capability Profiler with Auto Configuration")
    print("=" * 60)
    
    try:
        # Create detector
        profiler = GPUBaseCapability(
            platform_idx=args.platform,
            device_idx=args.device,
            verbose=not args.quiet
        )
        
        if args.generate_config:
            # Generate configuration directly
            print("\nGenerating optimized test configuration...")
            config = profiler.generate_batch_configuration(
                output_file=args.config_output,
                config_name=args.config_output
            )
            
            # Also run basic tests to populate the report
            if not args.quiet:
                profiler.run_all_tests()
                profiler.print_report(detailed=args.detailed)
        else:
            # Run standard tests
            print("Running capability tests...")
            report = profiler.run_all_tests()
            
            # Print report
            profiler.print_report(detailed=args.detailed)
            
            # Save report
            if args.output:
                profiler.save_report(args.output)
            
            # Offer to generate configuration
            if not args.quiet:
                print("\n" + "="*60)
                print("Would you like to generate an optimized test configuration?")
                print("Run with --generate-config flag to auto-generate batch test config.")
                print("="*60)
        
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
