"""
MCPC Core Law: Physics Domain Interface Definition Specification (IDS)
----------------------------------------------------------------------
This file defines the physical measurement data hierarchy and entity types. 
It strictly separates universal traits from L2-specific assumptions.
"""

from dataclasses import dataclass
import numpy as np
from enum import Enum, auto

# =============================================================================
# [ABSTRACT / MCPC UNIVERSAL]
# Fundamental constants and status enums used across all simulation levels.
# =============================================================================

class PhysicalConstants:
    """Universal physical constants for high-fidelity space simulations."""
    G = 6.67430e-11          # Gravitational constant (m^3 kg^-1 s^-2)
    C = 299792458.0          # Speed of light (m/s)
    AU = 149597870700.0      # Astronomical Unit (m)

class ComponentHealthStatus(Enum):
    """General health status for hardware components (Sensors/Actuators)."""
    NOMINAL = auto()
    DEGRADED = auto()
    FAILED = auto()

class SpacecraftType(Enum):
    """
    Defines the role of the spacecraft within a formation.
    Essential for GNC logic to distinguish between the reference and followers.
    """
    CHIEF = auto()           # The formation reference or lead satellite
    DEPUTY = auto()          # A following or member satellite
    OBSERVER = auto()        # A non-member monitoring node

@dataclass
class PhysicalMeasurementBase:
    """
    Root class for any data generated by a physical sensor.
    Ensures that every measurement is tied to a specific simulation epoch.
    """
    phys_timestamp: float    # True simulation time of the measurement event


# =============================================================================
# [L2-SPECIFIC / POINT MASS APPROXIMATION]
# Implementation of relative measurements for the current formation level.
# =============================================================================

@dataclass
class MicrowaveISLMeasurement(PhysicalMeasurementBase):
    """
    L2-Specific Implementation: RF/Microwave-based relative measurement.
    Used for formation acquisition and maintenance at the point-mass level.
    """
    range_m: float           # Measured relative distance (m)
    azimuth_rad: float       # Measured azimuth angle (rad)
    elevation_rad: float     # Measured elevation angle (rad)
    signal_strength: float   # Normalized signal power [0.0 to 1.0]
    
    # [NOTE] In L3/L4, this may be replaced by specific Sensor Models 
    # (e.g., LiDAR, Vision) which will inherit from PhysicalMeasurementBase.
