"""
MCPC Core Cyber: ISL Network Router
-----------------------------------
Simulates the Cyber Domain's network layer for Inter-Satellite Links (ISL).
Wraps physical measurements into network frames and injects communication 
imperfections such as latency, jitter, and packet loss.
"""

import numpy as np
from typing import Optional
from mission_sim.core.cyber.ids import ISLNetworkFrame
from mission_sim.core.physics.ids import PhysicalMeasurementBase

class ISLRouter:
    """
    [L2-SPECIFIC / CYBER] Inter-Satellite Link Router.
    Acts as the data broker between the physical antenna and the GNC subsystem.
    Transforms objective physical events into delayed cyber information.
    """

    def __init__(
        self, 
        base_latency_s: float = 0.05,        # 50 ms baseline transmission/processing delay
        jitter_s: float = 0.01,              # 10 ms random delay variation (1-sigma)
        packet_loss_rate: float = 0.02,      # 2% probability of packet dropping
        random_seed: Optional[int] = None    # Seed for reproducibility
    ):
        """
        Initialize the network impairment parameters for the ISL.
        
        Args:
            base_latency_s: Minimum guaranteed time required for data to reach the destination.
            jitter_s: Standard deviation of the network delay (Gaussian noise).
            packet_loss_rate: Probability [0.0 to 1.0] that a packet is completely lost in transit.
            random_seed: Optional seed for the random number generator.
        """
        self.base_latency_s = float(base_latency_s)
        self.jitter_s = float(jitter_s)
        self.packet_loss_rate = float(packet_loss_rate)
        self._rng = np.random.default_rng(random_seed)

    def transmit(
        self, 
        payload: PhysicalMeasurementBase, 
        source_id: str, 
        dest_id: str, 
        current_time: float
    ) -> Optional[ISLNetworkFrame]:
        """
        [CYBER ROUTING]
        Attempt to route a physical measurement from the source to the destination.
        Applies packet loss and calculates the expected reception time (rx_time).
        
        Args:
            payload: The physical measurement generated by the sensor (e.g., ISLAntenna).
            source_id: String ID of the transmitting spacecraft.
            dest_id: String ID of the receiving spacecraft.
            current_time: The simulation epoch when the transmission begins.
            
        Returns:
            ISLNetworkFrame: The fully encapsulated network packet containing rx_time.
            None: If the packet was dropped due to simulated network loss.
        """
        # 1. Simulate Packet Loss (Dropped packets never reach the destination)
        if self._rng.random() < self.packet_loss_rate:
            return None

        # 2. Simulate Network Latency and Jitter
        # Use absolute Gaussian noise to prevent negative time jumps
        variable_delay = self._rng.normal(0.0, self.jitter_s)
        total_latency = self.base_latency_s + variable_delay
        
        # Calculate the exact epoch when the destination GNC will be allowed to read this data
        rx_time = current_time + total_latency

        # 3. Encapsulate and Route the Frame
        return ISLNetworkFrame(
            payload=payload,
            source_id=source_id,
            dest_id=dest_id,
            tx_time=float(current_time),
            rx_time=float(rx_time)
        )

    def __repr__(self) -> str:
        return (f"ISLRouter(Latency={self.base_latency_s}s, "
                f"Jitter={self.jitter_s}s, DropRate={self.packet_loss_rate * 100}%)")
