#!/usr/bin/env python3
# analysis/formation_evaluator.py
"""
MCPC L2 Formation Evaluator: Post-Processing for Formation Simulation
---------------------------------------------------------------------
Reads HDF5 files generated by FormationSimulation and computes:
- Cooling time (settling time after reconfiguration)
- Observation duty cycle (stable time / total time)
- Delta-V consumption for chief and deputies
- Steady-state RMSE of relative position/velocity
- Generates CSV report and diagnostic plots

Usage:
    python analysis/formation_evaluator.py --input data/formation_sim.h5 --output analysis_results/
"""

import os
import sys
import argparse
import numpy as np
import matplotlib.pyplot as plt
import h5py
import pandas as pd
from typing import Dict, List, Tuple, Optional


class FormationEvaluator:
    def __init__(self, filepath: str, output_dir: str = "analysis_results"):
        self.filepath = filepath
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

        with h5py.File(filepath, 'r') as f:
            self.times = f['epochs'][()] if 'epochs' in f else np.array([])
            self.chief_dv = f['accumulated_dvs'][()] if 'accumulated_dvs' in f else None
            self.deputy_data = {}
            self.deputy_targets = {}
            if 'formation' in f:
                formation_grp = f['formation']
                for dep_name in formation_grp.keys():
                    if dep_name.startswith('deputy_'):
                        dep_grp = formation_grp[dep_name]
                        dep_id = dep_name[7:]  # remove "deputy_"
                        self.deputy_data[dep_id] = {
                            'time': dep_grp['time'][()],
                            'rel_pos': dep_grp['rel_position'][()],
                            'rel_vel': dep_grp['rel_velocity'][()],
                            'control_force': dep_grp['control_force'][()],
                            'mode': dep_grp['mode'][()],
                        }
            if 'metadata/targets' in f:
                targets_grp = f['metadata/targets']
                for key in targets_grp.keys():
                    if key.startswith('deputy_'):
                        dep_id = key[7:]
                        self.deputy_targets[dep_id] = targets_grp[key][()]
        self.sim_duration_days = (self.times[-1] - self.times[0]) / 86400.0 if len(self.times) > 0 else 0
        self.position_threshold_m = 1.0
        self.velocity_threshold_mms = 10.0
        self.stable_window_samples = 3

    def _get_target(self, dep_id: str) -> np.ndarray:
        """Return target relative state (6,) for given deputy, zeros if not found."""
        return self.deputy_targets.get(dep_id, np.zeros(6))

    def compute_cooling_time(self, rel_pos: np.ndarray, times: np.ndarray,
                             mode_series: np.ndarray, target_pos: np.ndarray,
                             target_mode: int = 2) -> Tuple[float, float]:
        error_pos = rel_pos - target_pos
        pos_error_norm = np.linalg.norm(error_pos, axis=1)
        reconfig_indices = np.where(mode_series == target_mode)[0]
        if len(reconfig_indices) == 0:
            return np.nan, np.nan
        last_reconfig_idx = reconfig_indices[-1]
        reconfig_end_time = times[last_reconfig_idx]
        for i in range(last_reconfig_idx + 1, len(pos_error_norm) - self.stable_window_samples + 1):
            window = pos_error_norm[i:i + self.stable_window_samples]
            if np.all(window < self.position_threshold_m):
                stable_start_time = times[i]
                cooling_time = stable_start_time - reconfig_end_time
                return cooling_time, reconfig_end_time
        return np.nan, reconfig_end_time

    def compute_duty_cycle(self, rel_pos: np.ndarray, times: np.ndarray,
                           mode_series: np.ndarray, target_pos: np.ndarray,
                           exclude_modes: List[int] = [2]) -> float:
        error_pos = rel_pos - target_pos
        pos_error_norm = np.linalg.norm(error_pos, axis=1)
        stable = (pos_error_norm < self.position_threshold_m) & (~np.isin(mode_series, exclude_modes))
        if len(times) < 2:
            return np.nan
        dt = np.diff(times)
        stable_time = np.sum(dt * (stable[:-1].astype(float) + stable[1:].astype(float)) / 2.0)
        total_time = times[-1] - times[0]
        return stable_time / total_time if total_time > 0 else np.nan

    def compute_rmse(self, rel_pos: np.ndarray, rel_vel: np.ndarray,
                     mode_series: np.ndarray, target_pos: np.ndarray, target_vel: np.ndarray,
                     exclude_modes: List[int] = [2]) -> Tuple[float, float]:
        error_pos = rel_pos - target_pos
        error_vel = rel_vel - target_vel
        mask = ~np.isin(mode_series, exclude_modes)
        if not np.any(mask):
            return np.nan, np.nan
        pos_norm = np.linalg.norm(error_pos[mask], axis=1)
        vel_norm = np.linalg.norm(error_vel[mask], axis=1) * 1000
        rmse_pos = np.sqrt(np.mean(pos_norm**2))
        rmse_vel = np.sqrt(np.mean(vel_norm**2))
        return rmse_pos, rmse_vel

    def compute_delta_v(self) -> Dict[str, float]:
        dv_dict = {}
        if self.chief_dv is not None and len(self.chief_dv) > 0:
            dv_dict['chief_dv_mps'] = float(self.chief_dv[-1])
        else:
            dv_dict['chief_dv_mps'] = np.nan
        for dep_id, data in self.deputy_data.items():
            times = data['time']
            control_force = data['control_force']
            if len(times) < 2:
                dv_dict[f'{dep_id}_dv_mps'] = np.nan
                continue
            mass = 500.0
            dt = np.diff(times)
            force_mag = np.linalg.norm(control_force[:-1], axis=1)
            dv = np.sum(force_mag / mass * dt)
            dv_dict[f'{dep_id}_dv_mps'] = dv
        return dv_dict

    def generate_csv_report(self) -> str:
        rows = []
        for dep_id, data in self.deputy_data.items():
            target = self._get_target(dep_id)
            target_pos = target[:3]
            target_vel = target[3:]
            cooling_time, reconf_end = self.compute_cooling_time(
                data['rel_pos'], data['time'], data['mode'], target_pos, target_mode=2
            )
            duty_cycle = self.compute_duty_cycle(
                data['rel_pos'], data['time'], data['mode'], target_pos, exclude_modes=[2]
            )
            rmse_pos, rmse_vel = self.compute_rmse(
                data['rel_pos'], data['rel_vel'], data['mode'], target_pos, target_vel, exclude_modes=[2]
            )
            rows.append({
                'deputy_id': dep_id,
                'simulation_duration_days': self.sim_duration_days,
                'cooling_time_s': cooling_time,
                'reconfiguration_end_time_s': reconf_end,
                'duty_cycle': duty_cycle,
                'rmse_position_m': rmse_pos,
                'rmse_velocity_mms': rmse_vel,
            })
        dv_dict = self.compute_delta_v()
        rows.append({
            'deputy_id': 'CHIEF',
            'simulation_duration_days': self.sim_duration_days,
            'cooling_time_s': np.nan,
            'reconfiguration_end_time_s': np.nan,
            'duty_cycle': np.nan,
            'rmse_position_m': np.nan,
            'rmse_velocity_mms': np.nan,
        })
        df = pd.DataFrame(rows)
        csv_path = os.path.join(self.output_dir, 'formation_evaluation.csv')
        df.to_csv(csv_path, index=False)
        print(f"CSV report saved: {csv_path}")
        return csv_path

    def generate_plots(self):
        for dep_id, data in self.deputy_data.items():
            target = self._get_target(dep_id)
            target_pos = target[:3]
            target_vel = target[3:]
            fig, axes = plt.subplots(3, 1, figsize=(10, 12), sharex=True)
            fig.suptitle(f"Formation Evaluation: {dep_id}", fontsize=14, fontweight='bold')
            times_days = data['time'] / 86400.0
            error_pos = data['rel_pos'] - target_pos
            pos_error_norm = np.linalg.norm(error_pos, axis=1)
            error_vel = data['rel_vel'] - target_vel
            vel_error_norm = np.linalg.norm(error_vel, axis=1) * 1000
            force_mag = np.linalg.norm(data['control_force'], axis=1)

            axes[0].plot(times_days, pos_error_norm, 'b-', label='Position Error')
            axes[0].axhline(self.position_threshold_m, color='r', linestyle='--', label=f'Threshold ({self.position_threshold_m} m)')
            axes[0].set_ylabel('Position Error (m)')
            axes[0].legend()
            axes[0].grid(True, alpha=0.3)

            axes[1].plot(times_days, vel_error_norm, 'g-', label='Velocity Error')
            axes[1].axhline(self.velocity_threshold_mms, color='r', linestyle='--', label=f'Threshold ({self.velocity_threshold_mms} mm/s)')
            axes[1].set_ylabel('Velocity Error (mm/s)')
            axes[1].legend()
            axes[1].grid(True, alpha=0.3)

            axes[2].plot(times_days, force_mag, 'm-', label='Control force')
            axes[2].set_xlabel('Time (days)')
            axes[2].set_ylabel('Force (N)')
            axes[2].legend()
            axes[2].grid(True, alpha=0.3)

            mode = data['mode']
            for i in range(len(mode) - 1):
                if mode[i] != mode[i + 1]:
                    axes[0].axvline(times_days[i], color='gray', linestyle=':', alpha=0.5)

            plt.tight_layout()
            save_path = os.path.join(self.output_dir, f"{dep_id}_evaluation.png")
            plt.savefig(save_path, dpi=150)
            plt.close()
            print(f"Plot saved: {save_path}")

    def print_summary(self):
        print("\n" + "=" * 60)
        print("FORMATION SIMULATION EVALUATION SUMMARY")
        print("=" * 60)
        print(f"Simulation duration: {self.sim_duration_days:.2f} days")
        dv_dict = self.compute_delta_v()
        print(f"Chief ΔV: {dv_dict.get('chief_dv_mps', np.nan):.4f} m/s")
        for dep_id, data in self.deputy_data.items():
            target = self._get_target(dep_id)
            cooling, _ = self.compute_cooling_time(data['rel_pos'], data['time'], data['mode'], target[:3])
            duty = self.compute_duty_cycle(data['rel_pos'], data['time'], data['mode'], target[:3])
            rmse_pos, rmse_vel = self.compute_rmse(data['rel_pos'], data['rel_vel'], data['mode'], target[:3], target[3:])
            dv = dv_dict.get(f'{dep_id}_dv_mps', np.nan)
            print(f"\n--- {dep_id} ---")
            print(f"  Cooling time after reconfiguration: {cooling:.2f} s" if not np.isnan(cooling) else "  Cooling time: N/A")
            print(f"  Observation duty cycle: {duty*100:.2f}%" if not np.isnan(duty) else "  Duty cycle: N/A")
            print(f"  Steady-state RMSE position: {rmse_pos:.3f} m" if not np.isnan(rmse_pos) else "  RMSE position: N/A")
            print(f"  Steady-state RMSE velocity: {rmse_vel:.2f} mm/s" if not np.isnan(rmse_vel) else "  RMSE velocity: N/A")
            print(f"  Estimated ΔV: {dv:.4f} m/s" if not np.isnan(dv) else "  ΔV: N/A")


def main():
    parser = argparse.ArgumentParser(description="Formation Simulation Evaluator")
    parser.add_argument("--input", "-i", required=True, help="HDF5 simulation output file")
    parser.add_argument("--output", "-o", default="analysis_results", help="Output directory")
    parser.add_argument("--pos_threshold", type=float, default=1.0, help="Position threshold for stability (m)")
    parser.add_argument("--vel_threshold", type=float, default=10.0, help="Velocity threshold for stability (mm/s)")
    parser.add_argument("--stable_window", type=int, default=3, help="Consecutive samples for stable detection")
    args = parser.parse_args()

    evaluator = FormationEvaluator(args.input, args.output)
    evaluator.position_threshold_m = args.pos_threshold
    evaluator.velocity_threshold_mms = args.vel_threshold
    evaluator.stable_window_samples = args.stable_window

    evaluator.generate_csv_report()
    evaluator.generate_plots()
    evaluator.print_summary()


if __name__ == "__main__":
    main()
